package ui;

import model.Rental;
import model.User;
import service.RentalService;
import util.PDFGenerator;
import util.UITheme;
import util.ValidationUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 * ReportPanel - Generate and print rental invoices.
 */
public class ReportPanel extends JPanel {

    private final User          currentUser;
    private final RentalService service = new RentalService();

    private JTable            reportTable;
    private DefaultTableModel reportModel;
    private JTextField        searchField;

    public ReportPanel(User user) {
        this.currentUser = user;
        setLayout(new BorderLayout());
        setBackground(UITheme.PAGE_BG);
        setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));
        add(buildHeader(), BorderLayout.NORTH);
        add(buildTable(),  BorderLayout.CENTER);
        add(buildFooter(), BorderLayout.SOUTH);
        loadAll();
    }

    private JPanel buildHeader() {
        JPanel p = new JPanel(new BorderLayout());
        p.setBackground(UITheme.PAGE_BG);
        p.setBorder(BorderFactory.createEmptyBorder(0, 0, 16, 0));

        JLabel title = new JLabel("📊  Reports & Invoice Generation");
        title.setFont(UITheme.FONT_TITLE);
        title.setForeground(UITheme.TEXT_PRIMARY);
        p.add(title, BorderLayout.WEST);

        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        right.setBackground(UITheme.PAGE_BG);
        searchField = UITheme.styledField(18);
        JButton searchBtn = UITheme.primaryButton("Search");
        JButton clearBtn  = UITheme.warningButton("Clear");
        searchBtn.addActionListener(e -> loadFiltered(searchField.getText().trim()));
        clearBtn.addActionListener(e  -> { searchField.setText(""); loadAll(); });
        right.add(new JLabel("Search: ")); right.add(searchField);
        right.add(searchBtn); right.add(clearBtn);
        p.add(right, BorderLayout.EAST);
        return p;
    }

    private JScrollPane buildTable() {
        String[] cols = {"Rental ID","Customer","Vehicle","Reg No","Start","End","Return","Amount","Fine","Total Due","Status"};
        reportModel = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r,int c){return false;}};
        reportTable = new JTable(reportModel);
        UITheme.styleTable(reportTable);
        reportTable.getColumnModel().getColumn(0).setMaxWidth(75);

        JScrollPane scroll = new JScrollPane(reportTable);
        scroll.setBorder(BorderFactory.createLineBorder(new Color(220,220,220)));
        return scroll;
    }

    private JPanel buildFooter() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT, 12, 8));
        p.setBackground(UITheme.PAGE_BG);

        JButton invoiceBtn = UITheme.successButton("🖨  Print Invoice");
        invoiceBtn.setPreferredSize(new Dimension(160, 38));
        invoiceBtn.addActionListener(e -> printInvoice());

        JButton refreshBtn = UITheme.primaryButton("🔄 Refresh");
        refreshBtn.addActionListener(e -> loadAll());

        JLabel hint = new JLabel("Select a rental row, then click Print Invoice.");
        hint.setFont(UITheme.FONT_SMALL);
        hint.setForeground(UITheme.TEXT_SECONDARY);

        p.add(invoiceBtn); p.add(refreshBtn); p.add(hint);
        return p;
    }

    private void printInvoice() {
        int row = reportTable.getSelectedRow();
        if (row < 0) {
            ValidationUtil.showError(this, "Please select a rental record to print."); return; }

        int rentalId = Integer.parseInt(reportModel.getValueAt(row,0).toString());
        Rental r = service.getById(rentalId);
        if (r == null) { ValidationUtil.showError(this,"Rental not found."); return; }

        double totalDue = r.getTotalAmount() + r.getFineAmount();
        String[] lines = {
            "Invoice No    : INV-" + String.format("%05d", r.getRentalId()),
            "Generated By  : " + currentUser.getFullName(),
            "",
            "Customer      : " + r.getCustomerName(),
            "Vehicle       : " + r.getVehicleName() + "  (" + r.getVehicleRegNo() + ")",
            "",
            "Rental Start  : " + r.getStartDate(),
            "Rental End    : " + r.getEndDate(),
            "Return Date   : " + (r.getActualReturnDate() != null ? r.getActualReturnDate() : "Not returned"),
            "Status        : " + r.getStatus(),
            "",
            "Rental Amount : Rs. " + String.format("%.2f", r.getTotalAmount()),
            "Late Fine     : Rs. " + String.format("%.2f", r.getFineAmount()),
            "──────────────────────────────────",
            "TOTAL DUE     : Rs. " + String.format("%.2f", totalDue),
        };
        PDFGenerator.printInvoice(lines);
    }

    private void loadAll() { loadFiltered(""); }

    private void loadFiltered(String kw) {
        reportModel.setRowCount(0);
        List<Rental> list = kw.isEmpty() ? service.getAllRentals() : service.searchRentals(kw);
        for (Rental r : list) {
            double totalDue = r.getTotalAmount() + r.getFineAmount();
            reportModel.addRow(new Object[]{
                r.getRentalId(), r.getCustomerName(), r.getVehicleName(),
                r.getVehicleRegNo(), r.getStartDate(), r.getEndDate(),
                r.getActualReturnDate(),
                String.format("₹ %.2f", r.getTotalAmount()),
                String.format("₹ %.2f", r.getFineAmount()),
                String.format("₹ %.2f", totalDue),
                r.getStatus()
            });
        }
    }
}
